In [44]:
import requests
import pandas as pd
import json
import regex as re
import geopandas
from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent="example app")
#import matplotlib.pyplot as plt
import numpy as np
import folium
from googlemaps import Client as GoogleMaps
import googlemaps

In [45]:
# Use CMS Dataset Versions UUID and not Dataset Type Identifier 
cms_data_version="7a101036-1595-443f-84b8-6bffca1786b8"
resp = requests.get(f"https://data.cms.gov/data-api/v1/dataset/{cms_data_version}/data")


headers = {
    'accept': 'application/json',
}

y=0
dflist=[]
size1=5000 # determined by the data.cms.gov as max rows per call
rows=5000 # Check the data documentation to see the number of rows, this determines the number of loops to run below
looplength=1 + rows//size1

for x in range(looplength):
    offset1=y+x*size1
    #change params to ensure number of rows matches interest
    params = {
        'offset': offset1,
        'size': size1,
    }
    response = requests.get(f"https://data.cms.gov/data-api/v1/dataset/{cms_data_version}/data",
        params=params,
        headers=headers,
    )
    df=pd.read_json(json.dumps(response.json()))
    dflist.append(df)

full_data1 = pd.concat(dflist)
#print(full_data)
#print(full_data.columns)
#full_data=full_data.dropna()

/var/folders/l_/km51gp91251bkt2xgwqlv_5c0000gp/T/ipykernel_2031/1637711426.py:27: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df=pd.read_json(json.dumps(response.json()))
/var/folders/l_/km51gp91251bkt2xgwqlv_5c0000gp/T/ipykernel_2031/1637711426.py:27: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df=pd.read_json(json.dumps(response.json()))

In [46]:
print(full_data1)

                        NPI                        PROVIDER NAME  \
0     1003081399 1013055110  BAART BEHAVIORAL HEALTH SERVICES IN
1                1003150004                 AMS OF WISCONSIN LLC
2                1003362484                         BHG XLII LLC
3                1003368945                         RTS EDGEWOOD
4                1003571647        METRO TREATMENT OF FLORIDA LP
...                     ...                                  ...
1438             1992835896      NEW BRUNSWICK COUNSELING CENTER
1439             1992861553          AEGIS TREATMENT CENTERS LLC
1440             1992861694  WESTSIDE METHADONE TREATMENT PROGRA
1441             1992941702          CARNEGIE HILL INSTITUTE INC
1442             1790700904                ATS AT JHBMC MFL BLDG

                 ADDRESS LINE 1                       ADDRESS LINE 2  \
0               617 COMSTOCK RD                                STE 5
1         9532 E 16 FRONTAGE RD                              STE 100
2         5715 PRINCESS ANNE RD
3          2205 PULASKI HIGHWAY
4     1241 BLANDING BLVD, STE 5       NEW SEASON TREATMENT CENTER 21
...                         ...                                  ...
1438                605 HIGH ST  BURLINGTON COMPREHENSIVE COUNSELING
1439      660 E LOS ANGELES AVE                               STE B2
1440             1301 PIERCE ST
1441              116 E 92ND ST                                BSMNT
1442           5200 EASTERN AVE                               FL 6-E

                CITY STATE         ZIP MEDICARE ID EFFECTIVE DATE       PHONE
0             BERLIN    VT  05602-8498                   1/1/2020  8022232003
1           ONALASKA    WI  54650-6742                   1/1/2020  9202322332
2     VIRGINIA BEACH    VA  23462-3222                   1/1/2020  7579620748
3           EDGEWOOD    MD       21040                 10/13/2020  4434569001
4        ORANGE PARK    FL  32065-5908                   1/1/2020  9046700820
...              ...   ...         ...                        ...         ...
1438     MOUNT HOLLY    NJ  08060-1022                  4/25/2022  6092673610
1439     SIMI VALLEY    CA  93065-1884                   1/1/2020  8055221844
1440   SAN FRANCISCO    CA  94115-4005                   1/1/2020  4154319000
1441        NEW YORK    NY  10128-1620                   1/1/2020  2122897166
1442       BALTIMORE    MD  21224-2734                   7/1/1966  4105500004

[1443 rows x 9 columns]

In [47]:
full_data=pd.read_csv('/Users/manaskaushik/Documents/OpiodTreat/full_data.csv')

In [48]:
fd=pd.merge(left=full_data1, right=full_data, left_on='NPI', right_on='NPI', how='outer')

In [49]:
fd=fd[fd['lat'].isna()]
fd

,NPI,PROVIDER NAME_x,ADDRESS LINE 1_x,ADDRESS LINE 2_x,CITY_x,STATE_x,ZIP_x,MEDICARE ID EFFECTIVE DATE_x,PHONE_x,Unnamed: 0,...,ADDRESS LINE 1_y,ADDRESS LINE 2_y,CITY_y,STATE_y,ZIP_y,MEDICARE ID EFFECTIVE DATE_y,PHONE_y,address,lat,lon
2,1003362484,BHG XLII LLC,5715 PRINCESS ANNE RD,,VIRGINIA BEACH,VA,23462-3222,1/1/2020,7579620748,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1003571647,METRO TREATMENT OF FLORIDA LP,"1241 BLANDING BLVD, STE 5",NEW SEASON TREATMENT CENTER 21,ORANGE PARK,FL,32065-5908,1/1/2020,9046700820,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,1003969767,RICHMOND TREATMENT CENTER LLC,4265 S A ST,,RICHMOND,IN,47374-6049,1/1/2020,7659628843,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,1013141977,DISCOVERY HOUSE BC LLC,3438 ROUTE 764,DISCOVERY HOUSE DUNCANSVILLE DHBC,DUNCANSVILLE,PA,16635-7803,1/1/2020,8149447000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,1013345065,MONTEFIORE MOUNT VERNON HOSPITAL,3 S 6TH AVE,,MOUNT VERNON,NY,10550-3197,2/7/2021,9146648000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3069,1972661411,OPERATION PAR INC,6150 150TH AVE N,NATC CLEARWATER OPERATION PAR INC,CLEARWATER,FL,33760-2138,1/1/2020,7275074673,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3081,1972880417,AUGUSTA ADDICTION ASSOCIATES,600 COMMERCIAL CT,STE A,SAVANNAH,GA,31406-3671,1/1/2020,9123524357,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3086,1982215299,"PINNACLE TREATMENT CENTERS OH-XIII,",8500 BILSTEIN BLVD,,HAMILTON,OH,45015-2218,9/23/2021,5132859583,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3096,1992031371,SHELBY COUNTY TREATMENT CENTER,750 HIGHWAY 31 S,,ALABASTER,AL,35007-4627,1/1/2020,2052160200,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3114,1992758361,"START TREATMENT & RECOVERY CENTERS,",2191 3RD AVE,,NEW YORK,NY,10035-3520,1/1/2020,2123485650,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:

gmaps = googlemaps.Client(key=xxx)

39.0724561

In [55]:
fd.columns

Index(['NPI', 'PROVIDER NAME_x', 'ADDRESS LINE 1_x', 'ADDRESS LINE 2_x',
       'CITY_x', 'STATE_x', 'ZIP_x', 'MEDICARE ID EFFECTIVE DATE_x', 'PHONE_x',
       'Unnamed: 0', 'level_0', 'index', 'PROVIDER NAME_y', 'ADDRESS LINE 1_y',
       'ADDRESS LINE 2_y', 'CITY_y', 'STATE_y', 'ZIP_y',
       'MEDICARE ID EFFECTIVE DATE_y', 'PHONE_y', 'address', 'lat', 'lon'],
      dtype='object')

In [51]:
fd=fd.reset_index(drop=True)
geolat=[]
geolong=[]
for z in range(len(fd)): 
    x1=re.split(r',|( ste)|( st)',  fd.loc[z,"ADDRESS LINE 1_x"].capitalize())[0]
    x2=fd.loc[z,"ADDRESS LINE 2_x"]
    x3=fd.loc[z,"CITY_x"].capitalize()
    x4=fd.loc[z,"STATE_x"]
    x5=fd.loc[z,"ZIP_x"][0:5]
    y=x1+","+x3+","+x4+","+x5+",US"
    fd.loc[z,"address"]=y
    try:
        xlat=gmaps.geocode(y)[0]['geometry']['location'] ['lat']
        xlon=gmaps.geocode(y)[0]['geometry']['location'] ['lng']
        geolat.append(xlat)
        geolong.append(xlon)
    except:
        xlat=np.nan
        xlon=np.nan
        geolat.append(np.nan)
        geolong.append(np.nan)
    print(xlat)
    print(xlon)

36.8399115
-76.18386029999999
30.1256258
-81.79199179999999
39.826817
-84.8429589
40.4617039
-78.4266218
40.9109397
-73.8386441
39.7107805
-105.0548739
40.7856092
-73.9458441
34.2049074
-86.87521939999999
40.8132003
-96.65943759999999
36.3970254
-82.48910850000001
41.11920569999999
-87.85663090000001
41.3105518
-72.9101014
47.225172
-122.4351003
42.9902196
-71.4638398
34.2210083
-85.1556037
46.6888084
-68.0111735
37.3942882
-77.4287403
40.7137873
-73.9958864
40.7138376
-73.9951519
41.61323180000001
-87.6069893
40.7390729
-73.9750165
40.7856092
-73.9458441
41.6190503
-80.2024349
42.450927
-82.9271033
42.189295
-71.7588382
43.187051
-71.5248459
40.3339994
-75.144277
36.83383500000001
-76.32110899999999
48.07528569999999
-123.1215889
40.663909
-73.9971896
31.2387103
-85.5413315
42.9072746
-78.86697459999999
41.8967625
-87.6363993
34.158709
-118.3962738
33.905458
-84.2166404
39.265571
-80.372936
39.9937828
-82.9919105
40.1915127
-74.86830259999999
41.113553
-85.1449039
37.799443
-121.230011
33.3682008
-86.93972199999999
40.3182846
-76.8565566
42.1174204
-86.4340326
36.05996
-115.0042673
33.8596342
-84.60529389999999
39.5987215
-110.7993199
45.0275126
-84.6747523
38.9063765
-84.5494068
36.6933756
-79.83054969999999
38.6381237
-121.4585237
39.9505591
-74.1422086
40.2841978
-111.6918265
39.1589053
-78.1581844
32.7878602
-97.057715
33.7458927
-117.8369582
39.4412213
-74.7077807
41.6737572
-87.79727439999999
36.1304974
-115.1081755
29.8279998
-81.32097449999999
38.7887966
-83.559823
33.8414415
-116.5452014
39.6824948
-78.7341407
36.6054446
-79.52675280000001
39.9513162
-75.15619749999999
40.9142599
-74.1730745
36.1129514
-79.7808879
35.6158714
-77.4127745
39.8350151
-75.0051866
39.3137019
-76.6177818
41.2232525
-73.2188109
39.8532254
-74.1807397
39.9274136
-83.8349971
34.2677467
-77.9321982
43.0989333
-79.0495598
39.7245999
-75.03473819999999
34.0691304
-117.6521657
39.1265831
-121.5615238
38.9843339
-76.5385044
36.0560016
-89.3771778
32.8147394
-97.4084109
43.44784079999999
-71.6268221
42.1225381
-80.08863649999999
36.2973636
-86.69590199999999
40.7016194
-84.0894984
34.0191626
-118.157438
39.7072701
-104.9261877
36.1373521
-115.137396
41.2293739
-87.8080102
41.2622344
-95.8705452
31.1990792
-97.4408397
33.5782736
-84.383404
34.3521484
-119.0664712
38.88555119999999
-76.9739373
40.6807535
-74.49745349999999
48.1118898
-123.4353974
27.5445981
-99.4814024
33.4344588
-111.8390892
31.7779945
-106.4793954
34.7662868
-87.67610959999999
38.23816830000001
-76.5263099
34.9624237
-85.1964496
38.2781642
-77.448639
40.9895423
-80.63758240000001
38.0317347
-78.4537692
35.78618
-82.5384206
37.5310878
-77.42277469999999
39.9400824
-75.2554241
39.551253
-76.363688
42.3636637
-71.05966599999999
37.0473126
-81.7811158
40.4413965
-74.2305425
42.2760775
-83.7810143
40.68783
-73.8683823
48.7938779
-122.6261148
37.2893613
-83.20843789999999
47.4417225
-122.236352
39.9415367
-75.2651824
34.9116304
-85.1050199
58.30025959999999
-134.4063492
40.800674
-73.935513
37.9801903
-122.5219237
39.61574239999999
-86.087785
41.1357424
-75.36448
39.3628226
-76.5516906
36.9198185
-94.8393344
31.2368995
-81.5394864
30.7615259
-81.60651949999999
41.9532426
-87.6784232
38.8250298
-104.7824384
41.2456338
-75.876361
41.2293739
-87.8080102
34.7832365
-84.7963697
42.9691408
-71.4801653
39.9415367
-75.2651824
40.7533658
-74.2046398
42.2411424
-87.97623949999999
34.6864255
-77.0740971
33.9123167
-84.7978278
40.697189
-73.93489799999999
41.0036719
-80.34700900000001
45.5042597
-122.4944507
35.6030514
-87.0640653
33.8708211
-87.26670999999999
36.3157652
-119.2913175
47.5875158
-122.3210854
30.6282135
-88.14824159999999
36.185185
-81.1475081
40.2723128
-78.8564892
39.802325
-89.6399217
33.0173703
-96.97922009999999
38.7893303
-90.5373307
40.8545243
-73.89092509999999
33.0947564
-83.2384514
45.5162211
-122.6388032
37.5054726
-77.5973449
37.79814
-81.11335849999999
37.583989
-84.290133
38.340717
-75.1228405
33.4113576
-111.681956
40.6424475
-111.938113
33.4356436
-112.0746972
39.0778452
-108.5046932
39.2877228
-76.5450003
39.2818101
-84.50064379999999
32.7683491
-96.6156699
39.8944884
-83.8084026
29.1201946
-81.0014544
37.0736845
-121.6051742
39.1173436
-94.62079179999999
36.833121
-87.4764544
33.4342388
-112.0830108
40.2042377
-79.6205961
40.3071116
-79.52189059999999
34.9155606
-81.0022578
35.4357554
-97.61248069999999
41.0523888
-73.54388639999999
32.7915152
-115.5549244
36.9186994
-121.7708782
38.2200151
-85.5726598
42.1659064
-72.633996
35.8050562
-80.8510324
61.5734207
-149.3878624
42.5654062
-83.8068543
37.7835636
-87.07409419999999
39.2645769
-81.5028476
33.9244755
-118.2648661
39.3311627
-76.63525340000001
35.5260009
-82.95089089999999
41.5234885
-87.558379
41.6907377
-71.16515849999999
40.4607356
-78.40852509999999
30.1567138
-82.643957
48.0535411
-122.1907922
37.0976596
-113.5755471
26.1918058
-80.1144138
33.4551536
-111.9260961
41.5925282
-93.63337639999999
41.3588799
-71.8354075
32.7766111
-117.158506
40.64246989999999
-111.8875067
37.741553
-122.1497236
33.7195497
-78.9316087
39.6405843
-78.8596517
46.97883909999999
-123.8144777
33.7985736
-118.1933438
39.1446272
-78.15025240000001
34.0744545
-118.0337723
39.7787207
-86.1581262
39.5382715
-107.3255235
34.9798236
-85.4220265
37.7800474
-122.4126387
28.3056447
-81.4152622
41.3074001
-72.90961779999999
39.1558248
-84.25758859999999
35.0767363
-106.5848717
40.064148
-80.571114
42.4530756
-83.19989699999999
33.6633528
-112.0297998
43.58414459999999
-116.355289
33.4867319
-112.0828159
39.626045
-77.8120234
32.373458
-90.147274
40.2111843
-76.9637332
34.4829412
-81.9387976
30.4998048
-88.33300249999999
61.1899785
-149.8901682
34.5084312
-119.7310213
39.2246072
-119.7078532
35.057011
-83.936227
44.5407015
-69.67381739999999
39.0514322
-74.84365389999999
33.9976946
-96.5187679
33.8540693
-118.1935615
35.6697191
-78.4787351
29.8905715
-95.5803382
29.4295044
-98.53894679999999
39.8586701
-79.9457202
34.9632794
-90.14543979999999
34.0480081
-118.3464231
40.6274818
-79.58549889999999
44.7985488
-73.0927884
34.0136435
-81.13430819999999
30.6018679
-87.12821989999999
42.3943677
-83.10102210000001
41.5062975
-87.65769739999999
32.3213663
-111.0088108
42.395905
-88.17892599999999
38.4823166
-107.8757192
38.3840286
-85.6884192
37.6910156
-77.54534129999999
37.6055987
-120.9381057
37.3165325
-76.73303949999999
39.3123401
-76.58369619999999
33.8061426
-117.9848556
40.7515847
-111.886211
38.1906545
-79.02500169999999
38.1906545
-79.02500169999999
40.7656562
-73.95430089999999
44.1010698
-69.1204743
40.4311796
-79.26086900000001
39.2005282
-76.7375414
40.5666338
-105.0374524
27.9081009
-82.7200092
32.0056463
-81.1085313
39.3436102
-84.51185500000001
33.2129759
-86.7878581
40.8079572
-73.9312302

In [ ]:
fd=fd.rename({'PROVIDER NAME_x':'PROVIDER NAME', 'ADDRESS LINE 1_x':'ADDRESS LINE 1', 'ADDRESS LINE 2_x':'ADDRESS LINE 2',
       'CITY_x':'CITY', 'STATE_x':'STATE', 'ZIP_x':'ZIP_x', 'MEDICARE ID EFFECTIVE DATE_x': 'MEDICARE ID EFFECTIVE DATE', 'PHONE_x':'PHONE'})
fd=fd.drop(axis=1, 'PROVIDER NAME_y', 'ADDRESS LINE 1_y',
       'ADDRESS LINE 2_y', 'CITY_y', 'STATE_y', 'ZIP_y',
       'MEDICARE ID EFFECTIVE DATE_y', 'PHONE_y')

In [53]:
fd['lat']=geolat
fd['lon']=geolong
print(fd['lat'])
fd.to_csv('/Users/manaskaushik/Documents/OpiodTreat/suppl.csv')

0      36.839911
1      30.125626
2      39.826817
3      40.461704
4      40.910940
         ...
262    27.908101
263    32.005646
264    39.343610
265    33.212976
266    40.807957
Name: lat, Length: 267, dtype: float64

In [54]:
print(fd)

            NPI                      PROVIDER NAME_x  \
0    1003362484                         BHG XLII LLC
1    1003571647        METRO TREATMENT OF FLORIDA LP
2    1003969767        RICHMOND TREATMENT CENTER LLC
3    1013141977               DISCOVERY HOUSE BC LLC
4    1013345065     MONTEFIORE MOUNT VERNON HOSPITAL
..          ...                                  ...
262  1972661411                    OPERATION PAR INC
263  1972880417         AUGUSTA ADDICTION ASSOCIATES
264  1982215299  PINNACLE TREATMENT CENTERS OH-XIII,
265  1992031371       SHELBY COUNTY TREATMENT CENTER
266  1992758361  START TREATMENT & RECOVERY CENTERS,

              ADDRESS LINE 1_x                   ADDRESS LINE 2_x  \
0        5715 PRINCESS ANNE RD
1    1241 BLANDING BLVD, STE 5     NEW SEASON TREATMENT CENTER 21
2                  4265 S A ST
3               3438 ROUTE 764  DISCOVERY HOUSE DUNCANSVILLE DHBC
4                  3 S 6TH AVE
..                         ...                                ...
262           6150 150TH AVE N  NATC CLEARWATER OPERATION PAR INC
263          600 COMMERCIAL CT                              STE A
264         8500 BILSTEIN BLVD
265           750 HIGHWAY 31 S
266               2191 3RD AVE

             CITY_x STATE_x       ZIP_x MEDICARE ID EFFECTIVE DATE_x  \
0    VIRGINIA BEACH      VA  23462-3222                     1/1/2020
1       ORANGE PARK      FL  32065-5908                     1/1/2020
2          RICHMOND      IN  47374-6049                     1/1/2020
3      DUNCANSVILLE      PA  16635-7803                     1/1/2020
4      MOUNT VERNON      NY  10550-3197                     2/7/2021
..              ...     ...         ...                          ...
262      CLEARWATER      FL  33760-2138                     1/1/2020
263        SAVANNAH      GA  31406-3671                     1/1/2020
264        HAMILTON      OH  45015-2218                    9/23/2021
265       ALABASTER      AL  35007-4627                     1/1/2020
266        NEW YORK      NY  10035-3520                     1/1/2020

        PHONE_x  Unnamed: 0  ...  ADDRESS LINE 1_y  ADDRESS LINE 2_y CITY_y  \
0    7579620748         NaN  ...               NaN               NaN    NaN
1    9046700820         NaN  ...               NaN               NaN    NaN
2    7659628843         NaN  ...               NaN               NaN    NaN
3    8149447000         NaN  ...               NaN               NaN    NaN
4    9146648000         NaN  ...               NaN               NaN    NaN
..          ...         ...  ...               ...               ...    ...
262  7275074673         NaN  ...               NaN               NaN    NaN
263  9123524357         NaN  ...               NaN               NaN    NaN
264  5132859583         NaN  ...               NaN               NaN    NaN
265  2052160200         NaN  ...               NaN               NaN    NaN
266  2123485650         NaN  ...               NaN               NaN    NaN

    STATE_y ZIP_y MEDICARE ID EFFECTIVE DATE_y PHONE_y  \
0       NaN   NaN                          NaN     NaN
1       NaN   NaN                          NaN     NaN
2       NaN   NaN                          NaN     NaN
3       NaN   NaN                          NaN     NaN
4       NaN   NaN                          NaN     NaN
..      ...   ...                          ...     ...
262     NaN   NaN                          NaN     NaN
263     NaN   NaN                          NaN     NaN
264     NaN   NaN                          NaN     NaN
265     NaN   NaN                          NaN     NaN
266     NaN   NaN                          NaN     NaN

                                              address        lat        lon
0    5715 princess anne rd,Virginia beach,VA,23462,US  36.839911 -76.183860
1          1241 blanding blvd,Orange park,FL,32065,US  30.125626 -81.791992
2                       4265 s a,Richmond,IN,47374,US  39.826817 -84.842959
3             3438 route 764,Duncansville,PA,16635,US  40.461704 -78.426622
4                3 s 6th ave,Mount vernon,NY,10550,US  40.910940 -73.838644
..                                                ...        ...        ...
262           6150 150th ave n,Clearwater,FL,33760,US  27.908101 -82.720009
263            600 commercial ct,Savannah,GA,31406,US  32.005646 -81.108531
264           8500 bilstein blvd,Hamilton,OH,45015,US  39.343610 -84.511855
265            750 highway 31 s,Alabaster,AL,35007,US  33.212976 -86.787858
266                 2191 3rd ave,New york,NY,10035,US  40.807957 -73.931230

[267 rows x 23 columns]